name: ktlint Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ambient
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run ktlintCheck
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          git checkout "$branch_name"
          ./gradlew ktlintCheck